<?php
   require_once(ROOT_PATH . "/ck/db/handler.php"); 
   require_once(ROOT_PATH . '/includes/html_dom_parser.php'); 
   require_once(ROOT_PATH . '/ck/baseball_file/process/functions.php');
    

 error_reporting(E_ALL);
ini_set('display_errors', 1);

$today = date("Y-m-d");
$games =  get_baseball_games_by_date($today);
echo "<pre>";


// LEFTY IS FROM .jSON Generated by a Schedule task, running a run_scraper.bat that bat runs a node js file named ScrapeStatMuse.js info came from https://www.statmuse.com/mlb/ask/team-batting-averages-vs-lefties-this-season

$today = date('Ydm');
$path = 'D:\\websites\\www.vrbmarketing.com\\ck\\baseball_file\\jobs\\scripts';
$jsonFile = $path . "\\lefty_{$today}.json";
$lefty = false;

if (file_exists($jsonFile)) {
   // echo "✅ Archivo encontrado: $jsonFile<br><br>";

    $jsonContent = file_get_contents($jsonFile);
    $dataArray = json_decode($jsonContent, true);
    $lefty = true;
    echo '<pre>';
   
} else {
    $lefty = false;
    echo "❌ Error: No se encontró el archivo en: $jsonFile";
}

//exit;
if(!empty($games) && $lefty){

$fields = " team_id,espn_small_name ";
$index = "espn_small_name";
$teams =  get_baseball_stadium_custom_fields($fields,$index);

//print_r($teams);
//print_r($dataArray);

}

// Mostrar el resultado
if(!empty($dataArray)){
    $new_array = array();
   
   foreach ($dataArray as $entry) {
    //echo $entry['team'] . ' / ' . $entry['era'] . "<br>";
      if(isset($teams[$entry['team']]["team_id"])){
       $new_array[$teams[$entry['team']]["team_id"]]['team'] = $entry['team'];
       $new_array[$teams[$entry['team']]["team_id"]]['avg'] = $entry['avg'];
      } else {
        echo "NO EXISTE ".$entry['team']."<BR>";
      } 


 }



 if(!empty($new_array)){
    foreach ($games as $game) {
        if(isset($new_array[$game->vars['team_away']]['avg'])){
        $game->vars['lefty_away'] = $new_array[$game->vars['team_away']]['avg'];
        }
        if(isset($new_array[$game->vars['team_home']]['avg'])){
         $game->vars['lefty_home'] = $new_array[$game->vars['team_home']]['avg'];
        }
        echo $game->update(array('lefty_away','lefty_home'));
        print_r($game);
           echo "Updated ID: ".$game->vars['id']."<BR>";

     }   

 }   
  

}

print_r($new_array);

?>